services:
    streamtube-app-dev:
      image: node:trixie-slim
      ports:
        - 127.0.0.1:8001:${PORT}
      volumes:
        - ./backend/app:/app/
      working_dir: /app 
      command: sh -c "npm run dev"
      depends_on:
        - mongodb
        - postgres
        - bucket-storage
      networks:
        - streamtube-dev
      user: 1000:1000

    video-transcoder-worker-dev:
      build:
        context: ./backend/videoTranscoder
        dockerfile: Dockerfile.ffmpeg
      image: ffmpeg-node
      volumes:
        - ./backend/videoTranscoder:/app/
      working_dir: /app
      user: 1000:1000
      stdin_open: true
      tty: true
      networks:
        - streamtube-dev
      # DEV ONLY: Simulate KEDA "Scale-to-Zero" behavior.
      # In Production (K8s), KEDA triggers this container only when messages exist.
      # In Docker Compose, KEDA is absent, so we use this loop to keep the 
      # container alive and polling for new work.  
      command: >
        sh -c "  
          while true; do
            echo 'Worker checking for jobs';
            npm start;
            echo 'Done or Empty. Sleeping 5s';
            sleep 5;
          done
        "
      # deploy:
      #     resources:
      #       limits:
      #         cpus: '8.0'  # Allocating 4 logical CPUs
      #         memory: 10G    # Allocating 8GB of memory

    mongodb:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      ports:
        - 127.0.0.1:27017:27017
      networks:
          - streamtube-dev
      volumes:
        - mongodb-dev-data:/data/db

    postgres:
      image: postgres:18
      restart: always
      environment:
        POSTGRES_USER: ${PGUSER}
        POSTGRES_PASSWORD: ${PGPASSWORD}
        POSTGRES_DB: ${PGDATABASE}
      ports:
        - "127.0.0.1:5432:5432"
      networks:
          - streamtube-dev
      volumes:
        - pg-dev-data:/var/lib/postgresql
    pgadmin:
      image: dpage/pgadmin4:latest
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      networks:
        - streamtube-dev
      ports:
        - "127.0.0.1:5050:80"
      depends_on:
        - postgres
      volumes:
        - pgadmin-dev-data:/var/lib/pgadmin

    bucket-storage:
      image: minio/minio:latest
      environment:
        MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
        MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
        # for event notfication
        MINIO_NOTIFY_AMQP_ENABLE_rabbitmq1: ${MINIO_NOTIFY_AMQP_ENABLE_rabbitmq1}
        MINIO_NOTIFY_AMQP_URL_rabbitmq1: ${MINIO_NOTIFY_AMQP_URL_rabbitmq1}
        MINIO_NOTIFY_AMQP_EXCHANGE_rabbitmq1: ${MINIO_NOTIFY_AMQP_EXCHANGE_rabbitmq1}
        MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_rabbitmq1: ${MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_rabbitmq1}
        MINIO_NOTIFY_AMQP_ROUTING_KEY_rabbitmq1: ${MINIO_NOTIFY_AMQP_ROUTING_KEY_rabbitmq1}
        MINIO_NOTIFY_AMQP_DELIVERY_MODE_rabbitmq1: ${MINIO_NOTIFY_AMQP_DELIVERY_MODE_rabbitmq1}
        MINIO_NOTIFY_AMQP_DURABLE_rabbitmq1: ${MINIO_NOTIFY_AMQP_DURABLE_rabbitmq1}
      depends_on:
        - rabbitmq
      ports:
        - 127.0.0.1:9000:9000  # HTTP port for MinIO
        - 127.0.0.1:9001:9001  # Port for MinIO Web UI (optional)
      networks:
          - streamtube-dev
      volumes:
        - minio-dev-data:/data
        - ./infra/s3/:/config/
      command: server /data --console-address ":9001"
      restart: always

    bucket-storage-init:
      image: minio/minio:latest
      depends_on:
        bucket-storage:
          condition: service_healthy
      environment:
        MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
        MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
        STORAGE_STS_USER: ${STORAGE_STS_USER}
        STORAGE_STS_PASSWORD: ${STORAGE_STS_PASSWORD}
        STORAGE_ENDPOINT: ${STORAGE_ENDPOINT}
      volumes:
        - ./infra/k8s/s3/init.sh/:/setup/init.sh
        - ./infra/k8s/s3/sts-streamtube-readonly-policy.json:/setup/sts-streamtube-readonly-policy.json    
      networks:
        - streamtube
      entrypoint: ["/bin/sh", "/setup/init.sh"]
  
      
    rabbitmq:
        image: rabbitmq:4-management
        volumes:
          - rabbitmq-dev-data:/var/lib/rabbitmq 
        environment:
          RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
          RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        ports:
          - 127.0.0.1:5672:5672
          - 127.0.0.1:15672:15672
        networks:
          - streamtube-dev
        healthcheck:
          test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
          interval: 5s
          timeout: 5s
          retries: 5
        restart: always

    rabbitmq-init:
        image: rabbitmq:4-management
        networks:
          - streamtube
        depends_on:
          rabbitmq:
            condition: service_healthy
        environment:
          # Use the SAME standard variable names here
          RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
          RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        volumes:
          - ./infra/k8s/rabbitmq/init.sh:/usr/local/bin/init.sh:ro
        entrypoint: ["/bin/sh", "/usr/local/bin/init.sh"]

volumes:
  mongodb-dev-data:
  minio-dev-data:
  pg-dev-data:
  pgadmin-dev-data:
  rabbitmq-dev-data:

networks:
  streamtube-dev: