apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../config
  - ingress/ingress.yaml
  - app/app.yaml
  - video-transcoder/video-transcoder-worker.yaml
  - rabbitmq/rabbitmq.yaml
  - minio/minio.yaml
  - postgres/postgres.yaml
  - mongodb/mongodb.yaml

secretGenerator:
  - name: app-secrets
    envs:
      - app/app.env

  - name: postgres-secrets
    envs:
      - postgres/postgres.env

  - name: mongodb-secrets
    envs:
      - mongodb/mongodb.env

  - name: minio-secrets
    envs:
      - minio/minio.env

  - name: rabbitmq-secrets
    envs:
      - rabbitmq/rabbitmq.env

  - name: video-transcoder-secrets
    envs:
      - video-transcoder/video-transcoder.env
    options:
      # because KEDA can't handle random suffix
      disableNameSuffixHash: true
